name: Validate index_html

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_index_html:
    name: Validate index html
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML generation
        run: |
          node scripts/generate_html.js
      - name: Assert git diff
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Differences found after (re)generation of the index.html"
            echo "Please refer to the README in order to learn how to generate the index.html properly."
            exit -1
          fi
